Task/follower groups
TheResonator/resonators-client pull request #22
Opened 2020-08-24 17:15 UTC by sOfekS

Added filter and select all functionalities to the group member page

![Annotation 2020-08-22 184500](https://user-images.githubusercontent.com/35032128/91075085-346ed780-e646-11ea-8efc-bc685da0dde0.png)

Also added an option to download all of the group's stats (all resonators) - needs to merge along with [server PR](url)

2020-08-25 15:08 UTC, TswusayonaTsamsiyu requested changes

2020-08-25 15:08 UTC, TswusayonaTsamsiyu commented on src/components/FollowerGroupMembers.js
> +                startAdornment: (
Looking at the screenshot you put in the PR, I think an `endAdornment` would look better.
Maybe that's just me though. Try it.

2020-08-25 15:08 UTC, TswusayonaTsamsiyu commented on src/components/FollowerGroupMembers.js
> +            </React.Fragment>);
Based on the screenshot, I think this column should be the leftmost (think of other apps you know, like Gmail).
Also I would remove the title and leave just the checkbox.

2020-08-25 18:30 UTC, sOfekS commented on src/components/FollowerGroupMembers.js
> +                marginTop: '0.5vh',
I've checked on multiple window sizes and it consistently stays vertically centered

2020-08-27 20:08 UTC, TswusayonaTsamsiyu approved these changes

2020-08-27 21:16 UTC, merged