Feature/advanced schedule
TheResonator/resonators-client pull request #33
Opened 2020-10-03 11:28 UTC by TswusayonaTsamsiyu

Added client-side support for changing resonator schedule intervals.

The [server PR](https://github.com/TheResonator/resonators-server/pull/40) must be merged and deployed too.

![image](https://user-images.githubusercontent.com/65984816/94990419-91827500-0584-11eb-8b67-232f298126ff.png)

2020-10-03 12:59 UTC, sOfekS requested changes
Is there a way to style the arrows? IMO it looks old-fashioned and doesn't fit right.

2020-10-03 12:59 UTC, sOfekS commented on src/components/EditResonator/Steps/schedule.js
> +                    endAdornment: <InputAdornment position="end">weeks</InputAdornment>,
Is `position` required?

2020-10-03 12:59 UTC, sOfekS commented on src/components/EditResonator/Steps/schedule.js
> +                {this.renderIntervalSelector()}
I think it should be only rendered when the "One Off" option isn't selected, doesn't make sense otherwise

2020-10-03 15:30 UTC, TswusayonaTsamsiyu commented on src/components/EditResonator/Steps/schedule.js
> +                    endAdornment: <InputAdornment position="end">weeks</InputAdornment>,
I think it fixes the CSS somehow. I'm just following the example in the documentation...

2020-10-03 15:30 UTC, TswusayonaTsamsiyu commented on src/components/EditResonator/Steps/schedule.js
> +                {this.renderIntervalSelector()}
That's correct. Will do.

2020-10-04 11:20 UTC, sOfekS approved these changes

2020-10-04 11:21 UTC, merged