resonator_questions (Criteria) reorder feature
TheResonator/resonators-client pull request #40
Opened 2020-10-30 03:49 UTC by raverside

2020-10-30 22:55 UTC, TswusayonaTsamsiyu commented
Could you please add a screenshot so I can see how it looks?

2020-10-30 23:12 UTC, TswusayonaTsamsiyu requested changes
Overall looks OK. Though I'd love to see a screenshot or GIF of the result.
You're very thorough for someone who just recently joined the project. Nice work!

I have some comments which I do hope you address. I think they are important.
Good luck! 😃

2020-10-30 23:12 UTC, TswusayonaTsamsiyu commented on src/components/ResonatorCriteriaSelection.js
> +        return (orderIndex >= 0) ? orderIndex : 999;
I'd say we probably also want unchecked questions to appear below all the checked questions.
Maybe make sure with Dror, but this seems to be the better UI design.

2020-10-30 23:12 UTC, TswusayonaTsamsiyu commented on src/sagas/resonatorCreation.js
> +        return target.resonatorApi.reorderCriterion(resonator[target.targetIdDbName], resonator.id, question.id, order);
Why not send a single request with the new question order?
It will avoid the multiple request overload, and will prevent potential weird bugs caused by partial order updates.
I think the `reorder` route on the server should expect a new ordering for all the questions at once.

2020-10-30 23:28 UTC, raverside commented on src/components/ResonatorCriteriaSelection.js
> +        return (orderIndex >= 0) ? orderIndex : 999;
and they do, or at least they're supposed to. On line 48 the unchecked questions get order 999, which sends them to the bottom of the list

2020-10-30 23:29 UTC, raverside commented on src/sagas/resonatorCreation.js
> +        return target.resonatorApi.reorderCriterion(resonator[target.targetIdDbName], resonator.id, question.id, order);
absolutely correct, laziness on my side here
I'll refactor this

2020-10-30 23:37 UTC, raverside commented on src/components/ResonatorCriteriaSelection.js
> +        return (orderIndex >= 0) ? orderIndex : 999;
https://www.loom.com/share/4ea7b4cf7307496dacc467700971548a

2020-10-30 23:39 UTC, TswusayonaTsamsiyu commented on src/components/ResonatorCriteriaSelection.js
> +        return (orderIndex >= 0) ? orderIndex : 999;
OMG it is freaking beautiful!!!

2020-10-31 21:34 UTC, TswusayonaTsamsiyu approved these changes
Just a small thing you didn't notice I guess...

2020-10-31 21:34 UTC, TswusayonaTsamsiyu commented on src/sagas/resonatorCreation.js
> +    var promisesStack = [];
You don't really need this variable anymore. You can just `return` with the api call :)

2020-10-31 22:27 UTC, merged