Activate/Deactivate criteria changes
TheResonator/resonators-client pull request #51
Opened 2020-12-05 12:58 UTC by rashmi-91

Activate/Deactivate criteria changes

Only active criterias will be available for selection in resonators

2020-12-08 13:11 UTC, raverside requested changes
A few minor changes, other than that looks good to me

2020-12-08 13:11 UTC, raverside commented on src/components/ResonatorCriteriaSelection.js
> +    let activeCriterions = _.filter(criterions, c => c.removed === false);
Please rename to criteria and activeCriteria. Also if you don't plan to reassign the value of the variable you should use `const`

2020-12-08 13:11 UTC, raverside commented on src/sagas/criteriaSaga.js
> +    let lastCriterions = yield select(criteriaSelector);
please rename to lastCriteria

2020-12-19 13:30 UTC, rashmi-91 commented on src/api/criteria.js
> +}
I can do this merge into single function. The reason i kept it separate is because, across the application they have separate methods created in similar situations. So thought will maintain the same, so that each functionalities are isolated in terms of business logic internally. Still, if you want me to change, i can do. Please confirm.

2020-12-20 13:31 UTC, raverside approved these changes

2020-12-20 15:48 UTC, merged